### ISSUE TITLE
is it worked for now?

### ISSUE THREAD

**Issue by Rainbowrain-TW** [gurubobnz/trello-json-viewer#1]
Hi gurubobnz, after download and try, it seems not work. Maybe I missed something?

**Comment by gurubobnz** [comment]
Hello! Sorry this is a very early push ... perhaps you can describe more what the problem is and I can help you?

**Comment by gurubobnz** [comment]
Also try pulling the latest changes - you need to place your trello.json file in the same directory. You might have trouble opening it from a local folder in Chrome, but Firefox works. If you host it on a web server it should be fine.

**Comment by Rainbowrain-TW** [comment]
Thank you for reply. With the latest version, it worked nicely. Seems still some feature need to completed. ex: card description. And I really need those descriptions.

My latest work use trello to record my task. and got be fired now haha. So I wanna keep those cards. But the exported json file looks horrible. After google, I find this repo. This is a good idea. Thank you.

**Comment by gurubobnz** [comment]
Yes, there is markdown in the descriptions that I am not doing anything about yet. Also there are obvious issues with layout for many lists - I am just wrapping them for now.
