### ISSUE TITLE
Card covers are missing labels, decorations

### ISSUE THREAD

**Issue by jreich888** [gurubobnz/trello-json-viewer#2]
If a card has labels, descriptions, comments, tasks, etc, in Trello, there are badges or icons on the card cover indicating their presence (and sometimes counts).  See the example from Trello welcome board, below.

![image](https://user-images.githubusercontent.com/7728190/90987630-4ca8fe80-e541-11ea-8f5a-1254e2ac62ec.png)

**Comment by jreich888** [comment]
Note: I have started to make changes to support this.  I need to talk to you about how I might be able to contribute to this project.

**Comment by gurubobnz** [comment]
Hi thanks for the issue. Happy to review a PR. Also you can email me at gurubob@gmail.com if that's useful for you.

**Comment by gurubobnz** [comment]
Closed by #3
